// Package intervals provides structures and functions for building intervals queries.
// Returns documents based on the order and proximity of matching terms.
package intervals

// AllOf represents the all_of interval query
type AllOf struct {
	Intervals []*Param `json:"intervals"`
	Filter    *Filter  `json:"filter,omitempty"`
	Ordered   bool     `json:"ordered,omitempty"`
	MaxGaps   int      `json:"max_gaps,omitempty"`
}

// NewParamAllOf creates a new AllOf instance for the intervals query parameters.
func NewParamAllOf(p []*Param) *AllOf {
	return &AllOf{Intervals: p}
}

// SetFilter sets the Filter for the AllOf.
// A rule used to filter returned intervals.
func (a *AllOf) SetFilter(f *Filter) *AllOf {
	a.Filter = f
	return a
}

// SetOrdered sets the Ordered for the AllOf.
// If true, intervals generated by the rules should appear in the specified order.
// Default is false.
func (a *AllOf) SetOrdered(value bool) *AllOf {
	a.Ordered = value
	return a
}

// SetMaxGaps sets the MaxGaps for the AllOf.
// The maximum allowed number of positions between the matching terms.
// Terms further apart than max_gaps are not considered matches.
// If max_gaps is not specified or is set to -1, terms are considered matches regardless of their position.
// If max_gaps is set to 0, matching terms must appear next to each other.
// Default is -1.
func (a *AllOf) SetMaxGaps(value int) *AllOf {
	a.MaxGaps = value
	return a
}
